/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
id INT GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1),
name varchar(100) not null,
date_of_birth date not null,
escape_attempts int not null,
neutered bool not null,
weight_kg decimal not null,
PRIMARY KEY (id)
);

ALTER TABLE animals ADD species varchar(100);
