/* Database schema to keep the structure of entire database. */

/*Animals Table*/

CREATE TABLE animals (
id INT GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1),
name varchar(100) not null,
date_of_birth date not null,
escape_attempts int not null,
neutered bool not null,
weight_kg decimal not null,
PRIMARY KEY (id)
);

ALTER TABLE animals ADD species varchar(100);

/*Owners Table*/

CREATE TABLE owners (
id INT GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1),
owner_id INT GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1), 
full_name varchar(100) not null,
age INT not null,
PRIMARY KEY (id),
   CONSTRAINT fk_owners
      FOREIGN KEY(owner_id) 
	  REFERENCES animals(id)
      ON DELETE SET NULL
);
ALTER TABLE animals ADD owner_id int;

/*Species  Table*/

CREATE TABLE species (
id INT GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1),
species_id INT GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1), 
name varchar(100) not null,
PRIMARY KEY (id),
   CONSTRAINT fk_species
      FOREIGN KEY(species_id) 
	  REFERENCES animals(id)
      ON DELETE SET NULL
);
ALTER TABLE animals ADD species_id int;
